#!/usr/bin/env bash
docker-compose up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===================== 🚀 Done 🚀 ===================

      Created by Lucas Apoena A. Rodrigues
      v.$version
      Access your new links:

      🌎 Zabbix Web: http://localhost:8080

===================== 🚀 Done 🚀 ==================="
